import { App } from './App';
import { appBootstrapper } from './appBootstrapper';
import {
  CHARACTER_ROUTE,
  CHARACTER_CREATE_ROUTE,
  CHARACTER_EDIT_ROUTE,
  CHARACTERS_ROUTE,
  CREATURE_ROUTE,
  CREATURE_CREATE_ROUTE,
  CREATURE_EDIT_ROUTE,
  CREATURES_ROUTE,
  LOGIN_ROUTE,
  MAGIC_ITEM_ROUTE,
  MAGIC_ITEM_CREATE_ROUTE,
  MAGIC_ITEM_EDIT_ROUTE,
  MAGIC_ITEMS_ROUTE,
  ROOT_ROUTE,
  SPELL_ROUTE,
  SPELL_CREATE_ROUTE,
  SPELL_EDIT_ROUTE,
  SPELLS_ROUTE,
  USERS_ROUTE
} from './routes';

export {
  App,
  appBootstrapper,
  CHARACTER_ROUTE,
  CHARACTER_CREATE_ROUTE,
  CHARACTER_EDIT_ROUTE,
  CHARACTERS_ROUTE,
  CREATURE_ROUTE,
  CREATURE_CREATE_ROUTE,
  CREATURE_EDIT_ROUTE,
  CREATURES_ROUTE,
  LOGIN_ROUTE,
  MAGIC_ITEM_ROUTE,
  MAGIC_ITEM_CREATE_ROUTE,
  MAGIC_ITEM_EDIT_ROUTE,
  MAGIC_ITEMS_ROUTE,
  ROOT_ROUTE,
  SPELL_ROUTE,
  SPELL_CREATE_ROUTE,
  SPELL_EDIT_ROUTE,
  SPELLS_ROUTE,
  USERS_ROUTE
};
