# frozen_string_literal: true

module Types
  module Inputs
    class CharacterInputType < Types::BaseInputObject
      argument :ac, Integer, required: true
      argument :acrobatics_mod, Integer, required: true
      argument :acrobatics_prof, String, required: true
      argument :age, Integer, required: true
      argument :alignment, String, required: true
      argument :animal_handling_mod, Integer, required: true
      argument :animal_handling_prof, String, required: true
      argument :arcana_mod, Integer, required: true
      argument :arcana_prof, String, required: true
      argument :armor_proficiencies, String, required: true
      argument :athletics_mod, Integer, required: true
      argument :athletics_prof, String, required: true
      argument :background, String, required: true
      argument :bonds, String, required: true
      argument :character_class, String, required: true
      argument :character_class_hit_dice, Integer, required: true
      argument :character_class_level, Integer, required: true
      argument :character_sub_class, String, required: true
      argument :charisma_mod, Integer, required: true
      argument :charisma_prof, String, required: true
      argument :charisma_save, Integer, required: true
      argument :charisma_score, Integer, required: true
      argument :condition_immunities, String, required: true
      argument :condition_resistances, String, required: true
      argument :condition_vulnerabilities, String, required: true
      argument :constitution_mod, Integer, required: true
      argument :constitution_prof, String, required: true
      argument :constitution_save, Integer, required: true
      argument :constitution_score, Integer, required: true
      argument :copper_pieces, Integer, required: true
      argument :damage_immunities, String, required: true
      argument :damage_resistances, String, required: true
      argument :damage_vulnerabilities, String, required: true
      argument :deception_mod, Integer, required: true
      argument :deception_prof, String, required: true
      argument :dexterity_mod, Integer, required: true
      argument :dexterity_prof, String, required: true
      argument :dexterity_save, Integer, required: true
      argument :dexterity_score, Integer, required: true
      argument :electrum_pieces, Integer, required: true
      argument :eyes, String, required: true
      argument :flaws, String, required: true
      argument :gold_pieces, Integer, required: true
      argument :hair, String, required: true
      argument :height, String, required: true
      argument :history_mod, Integer, required: true
      argument :history_prof, String, required: true
      argument :hp, Integer, required: true
      argument :ideals, String, required: true
      argument :initiative, Integer, required: true
      argument :insight_mod, Integer, required: true
      argument :insight_prof, String, required: true
      argument :intelligence_mod, Integer, required: true
      argument :intelligence_prof, String, required: true
      argument :intelligence_save, Integer, required: true
      argument :intelligence_score, Integer, required: true
      argument :intimidation_mod, Integer, required: true
      argument :intimidation_prof, String, required: true
      argument :investigation_mod, Integer, required: true
      argument :investigation_prof, String, required: true
      argument :languages, String, required: true
      argument :medicine_mod, Integer, required: true
      argument :medicine_prof, String, required: true
      argument :multiclass_class, String, required: true
      argument :multiclass_class_hit_dice, Integer, required: true
      argument :multiclass_class_level, Integer, required: true
      argument :multiclass_sub_class, String, required: true
      argument :name, String, required: true
      argument :nature_mod, Integer, required: true
      argument :nature_prof, String, required: true
      argument :passive_perception, Integer, required: true
      argument :perception_mod, Integer, required: true
      argument :perception_prof, String, required: true
      argument :performance_mod, Integer, required: true
      argument :performance_prof, String, required: true
      argument :personality_traits, String, required: true
      argument :persuasion_mod, Integer, required: true
      argument :persuasion_prof, String, required: true
      argument :platinum_pieces, Integer, required: true
      argument :proficiency_bonus, Integer, required: true
      argument :race, String, required: true
      argument :religion_mod, Integer, required: true
      argument :religion_prof, String, required: true
      argument :senses, String, required: true
      argument :silver_pieces, Integer, required: true
      argument :skin, String, required: true
      argument :sleight_of_hand_mod, Integer, required: true
      argument :sleight_of_hand_prof, String, required: true
      argument :speed, Integer, required: true
      argument :spell_slots_eighth, Integer, required: true
      argument :spell_slots_fifth, Integer, required: true
      argument :spell_slots_first, Integer, required: true
      argument :spell_slots_fourth, Integer, required: true
      argument :spell_slots_ninth, Integer, required: true
      argument :spell_slots_second, Integer, required: true
      argument :spell_slots_seventh, Integer, required: true
      argument :spell_slots_sixth, Integer, required: true
      argument :spell_slots_third, Integer, required: true
      argument :spellcasting_ability, String, required: true
      argument :spellcasting_modifier, Integer, required: true
      argument :spellcasting_save_dc, Integer, required: true
      argument :stealth_mod, Integer, required: true
      argument :stealth_prof, String, required: true
      argument :strength_mod, Integer, required: true
      argument :strength_prof, String, required: true
      argument :strength_save, Integer, required: true
      argument :strength_score, Integer, required: true
      argument :sub_race, String, required: true
      argument :survival_mod, Integer, required: true
      argument :survival_prof, String, required: true
      argument :tool_proficiencies, String, required: true
      argument :weapon_proficiencies, String, required: true
      argument :weight, String, required: true
      argument :wisdom_mod, Integer, required: true
      argument :wisdom_prof, String, required: true
      argument :wisdom_save, Integer, required: true
      argument :wisdom_score, Integer, required: true

      argument :character_attacks, [Types::Inputs::CharacterAttackInputType], required: true
      argument :character_feature_resources, [Types::Inputs::CharacterFeatureResourceInputType], required: true
      argument :character_features, [Types::Inputs::CharacterFeatureInputType], required: true
      argument :character_items, [Types::Inputs::CharacterItemInputType], required: true
      argument :character_spells, [Types::Inputs::CharacterSpellInputType], required: true
    end
  end 
end